-- functions/company/ensure_date.sql

-- 1. Version para TEXT
CREATE OR REPLACE FUNCTION company.ensure_date(val TEXT) RETURNS DATE AS $$
BEGIN
    IF val IS NULL OR TRIM(val) = '' THEN
        RETURN NULL;
    END IF;
    
    BEGIN RETURN val::DATE;               EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN RETURN TO_DATE(val, 'YYYY-MM-DD'); EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN RETURN TO_DATE(val, 'YYYY/MM/DD'); EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN RETURN TO_DATE(val, 'MM/DD/YYYY'); EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN RETURN TO_DATE(val, 'MM-DD-YYYY'); EXCEPTION WHEN OTHERS THEN NULL; END;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 2. Overloads
CREATE OR REPLACE FUNCTION company.ensure_date(val DATE) RETURNS DATE AS $$
BEGIN RETURN val; END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION company.ensure_date(val TIMESTAMP) RETURNS DATE AS $$
BEGIN RETURN val::DATE; END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION company.ensure_date(val TIMESTAMPTZ) RETURNS DATE AS $$
BEGIN RETURN val::DATE; END;
$$ LANGUAGE plpgsql;
